### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by orangecms** [pop-os/system76-scheduler#100]
This is a bit of a hard one to invest, I suppose - I'm using the stock Pop!_OS on a lemp10.

Anyway... I just found out about this scheduler because my laptop was getting hot for no obvious reason, losing battery quicker than usual. So I saw this process running at 100%, and had to restart it.

Now, I cannot tell what led to that condition, nor when exactly it started. If you can give me a hint what to look for, I'll gladly share my syslog etc.. I've checked `journalctl`, can't spot anything giving a clear hint, so I saved the last 4 hours for backup.

**Comment by mmstick** [comment]
Do you have the latest updates installed?

**Comment by orangecms** [comment]
Oh wow you're quick :sweat_smile: my current version of `system76-scheduler` is `2.0.0~1682509199~22.04~97a8617`.

**Comment by orangecms** [comment]
I see that another system update would get me the current HEAD, [837da2c](https://github.com/pop-os/system76-scheduler/commit/837da2c).

Anything in there that could help investigate or should fix the issue?

I think I recall having seen a process named pipewire in the ps tree... maybe that's related?
https://github.com/pop-os/system76-scheduler/commit/1b888cfb29ebb13f610ab1b1c05c97cee3e09576

**Comment by mmstick** [comment]
This was fixed last week in the 2.0.1 release
