### ISSUE TITLE
Does system76-scheduler replace Feral Interactive's gamemode?

### ISSUE THREAD

**Issue by Tiagoquix** [pop-os/system76-scheduler#110]
Hello there.

I would like to know if `system76-scheduler` basically does what Feral Interactive's `gamemode` does in terms of performance. I am new to Linux, and from my POV, they both seem to conflict.

Also, I'm not entirely sure if this is directly related to Pop/the scheduler, but could you please take a look at https://github.com/FeralInteractive/gamemode/issues/376?

Thanks in advance.

**Comment by Psyhackological** [comment]
From what I read the system76-scheduler conflicts with Feral Interactive gamemode. When both are turned on they will interfere each other to prioritize the processes so the game works better. There is even a line for game in the config:
https://github.com/pop-os/system76-scheduler/blob/master/data/config.kdl#L43
```kdl
        // Video games
        games nice=-5 io=(best-effort)0
```

so when using PopOS that uses this scheduler you shouldn't have any additional on-demand schedulers like Feral Interactive gamemode.
