### ISSUE TITLE
Use of brand name in standalone extension

### ISSUE THREAD

**Issue by mjakeman** [pop-os/system76-scheduler#16]
Hi, I've created a minimal extension to support using system76-scheduler without pop-shell (as pop-shell is not available on extensions.gnome.org). It can be found here: https://github.com/mjakeman/s76-scheduler-plugin/

As part of the [GNOME Extensions review guidelines](https://gjs.guide/extensions/review-guidelines/review-guidelines.html#copyrights-and-trademarks):

> Extensions MUST NOT include copyrighted or trademarked content without proof of express permission from the owner. Examples include: **Brand Names** and Phrases, Logos and Artwork, Audio, Video or Multimedia

Given that the project is called `system76-scheduler`, I'd just like to check that it's fine to use "System76 Scheduler" in the name of my extension? I've provided a [disclaimer](https://github.com/mjakeman/s76-scheduler-plugin/blob/ba6d3570acc05f812d91eef678efe371fa86a767/metadata.json#L3) that it is unofficial/not affiliated in the description.

**Comment by mmstick** [comment]
It's fine. No permission needed. It's just the generic name of the service. If it interfaces with System76 Scheduler, it shouldn't have to worry about naming it.
