### ISSUE TITLE
CFS tweaks might hurt performance

### ISSUE THREAD

**Issue by Alt37** [pop-os/system76-scheduler#2]
1) Value for "minimum_granularity" is not correct. It should be calculated like with such formula
`sched_min_granularity_ns=sched_latency_ns/sched_nr_latency`
sched_nr_latency = 8 on mainline
So for latency: 4ns:
minimum_granularity=4/8=0.5
For Zen kernel minimum_granularity=0.4 is correct because maintainers change "sched_nr_latency" value to "10" .
2) Reduction of "CPU migration cost" (sched_migration_cost) might hurt performance under load. That's the reason why this tweak has already been [dropped](https://github.com/zen-kernel/zen-kernel/commit/be5ba234ca0a5aabe74bfc7e1f636f085bd3823c) for Zen/Liquorix kernels

**Comment by mmstick** [comment]
Want to help out with a PR?

**Comment by Alt37** [comment]
I'm afraid that it will take too much time for me to compile, test and make a PR. Hope it will be fixed without my assistance.
--
I found a good source for the first suggestion (""minimum_granularity" value). Right in the linux kernel source code ([kernel/sched/fair.c](https://github.com/torvalds/linux/blob/master/kernel/sched/fair.c)):

```
/*
 * This value is kept at sysctl_sched_latency/sysctl_sched_min_granularity
 */
static unsigned int sched_nr_latency = 8;
```

**Comment by mmstick** [comment]
The [default sched_latency is 6ns](https://github.com/torvalds/linux/blob/master/kernel/sched/fair.c#L36), and 6ns / 8 = 0.75, so the default that we have with a migration of 0.75ns is correct. But we can drop the migration cost change.

**Comment by Alt37** [comment]
> The [default sched_latency is 6ns](https://github.com/torvalds/linux/blob/master/kernel/sched/fair.c#L36), and 6ns / 8 = 0.75, so the default that we have with a min granularity of 0.75ns is correct.

But in the current readme and even source code of system76-scheduler there are values for ["Responsive" CPU Scheduler Latency Configuration](https://github.com/pop-os/system76-scheduler#responsive) which aren't good for the most distros
```
latency: 4ns
minimum_granularity: 0.4ms
```

**Comment by mmstick** [comment]
That is because the [responsive config is the Zen config](https://github.com/zen-kernel/zen-kernel/blob/5.16/master/init/Kconfig#L127:L130), which is much more ideal for desktop responsiveness than what most distributions have as their defaults. There wouldn't be any point in having a responsive config if it had the same values the default config.
