### ISSUE TITLE
Config files under /usr/share/system76-scheduler/ are overwritten always on update when using the debian package.

### ISSUE THREAD

**Issue by techsy730** [pop-os/system76-scheduler#23]
The issue seems to be related to there being no `conffiles` file under `debian/`. Without this, dpkg thinks it is safe to overwrite wholesale, as if they were a binary file.

There are legitimate reasons to edit these config (for example, the top level `config.ron` file, which doesn't seem to have an equivalent potential location under `/etc`)

**Comment by jacobgkau** [comment]
From the [Debian manual page](https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles) you linked in your PR:

> If your program uses configuration files but also rewrites them on its own, it's best not to make them conffiles because dpkg will then prompt users to verify the changes all the time. 

As mentioned in https://github.com/pop-os/system76-scheduler/pull/24#issuecomment-1057102535, it's intended for files in `/usr/share` to be overwritten on upgrade. I think the actual issue might be that `/etc` doesn't support all of the same configuration, if that is the case. You should ideally be able to override everything from `/usr/share` using the `/etc` location, at least that's my understanding.

**Comment by techsy730** [comment]
Well, if you don't want them user configurable, fair enough. But

1. There should be a comment warning about the fact they will be overwritten on upgrade in the `/usr/share/` versions
2. There should be a way to disable or change entries in the `/usr/share/system76-scheduler/assignments/default.ron`

Have not tested placing `config.ron` straight in `/etc/system76-scheduler` yet. I'll see if it works.

I can file a new bug for this.

**Comment by mmstick** [comment]
We could add a `no-defaults: true` field to the main config to disable reading from `/usr/share`

**Comment by jacobgkau** [comment]
The defaults in `/usr/share` can be overridden by `/etc`, and the behavior (which is fairly standard) was documented by https://github.com/pop-os/system76-scheduler/pull/25.
