### ISSUE TITLE
Project name (System76 vs. Pop)

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/system76-scheduler#3]
Was there a reason this project was named system76-scheduler instead of pop-scheduler? Is anything about the project specific to System76 hardware? (This question just occurred to me while reading a news article about the release, and thinking about the relation between this and pop-shell, pop-launcher, etc.)

**Comment by mmstick** [comment]
Not in particular, besides being developed by System76 and not specific to Pop.

**Comment by mmstick** [comment]
We could change the name to something more unique, such as Scheduler76 or PopProc.

**Comment by jacobgkau** [comment]
I was just thinking about it from the perspective of e.g. [power-profiles-daemon](https://gitlab.freedesktop.org/hadess/power-profiles-daemon#system76-power) claiming system76-power could have been used as its base "if it was more of an upstream project instead of a PopOS!/System76 project," which, considering the license of system76-power, doesn't make a lot of sense unless they're referring to the name.

I suppose pop-scheduler would still imply a tie to Pop!_OS, which is (at least partially) why the new desktop environment components are being branded as cosmic-*, so other distros can package COSMIC without feeling like they're packaging Pop!_OS. It just seemed to me that the scheduler is a feature of Pop!_OS and that Pop!_OS is still less specific/would apply to more users of the project than System76.

We can probably close this if nobody else has strong feelings about it, although I like the idea of the shorter names too.

**Comment by jokeyrhyme** [comment]
The README includes this:

> Processes are regularly sweeped and assigned process priorities based on configuration files. When combined with [pop-shell](https://github.com/pop-os/shell/), foreground processes and their sub-processes will be given higher process priority.

These two sentences connect in my brain in a confusing way, haha

Does this need to be used with pop-os/shell in order for proper identification of foreground processes and their sub-processes?

Or does this functionality work regardless? Or is there some automatic benefit gained by using pop-os/shell that can be filled in with manual configuration in other environments?

**Comment by jacobgkau** [comment]
> Does this need to be used with pop-os/shell in order for proper identification of foreground processes and their sub-processes?

Yes, pop-shell is what would tell this daemon what's focused at any given time. Without pop-shell, this daemon would only be able to apply priorities set in the configuration files.

**Comment by jokeyrhyme** [comment]
Ah, awesome

So yeah, makes even more sense (to me) that the naming is not specific to PopOS

The full functionality of this daemon is available in any compositor/desktop-environment that calls appropriate DBus `SetForeground` method as appropriate

**Comment by jacobgkau** [comment]
> So yeah, makes even more sense (to me) that the naming is not specific to PopOS
> 
> The full functionality of this daemon is available in any compositor/desktop-environment that calls appropriate DBus `SetForeground` method as appropriate

I think you're missing my point that the daemon is even less specific to System76. The daemon is preinstalled on all computers with Pop!_OS. On the other hand, if you install any other Linux distribution on a System76 computer, you will not have the daemon preinstalled.

The pop-launcher backend can be used with any frontend that calls its JSON IPC interface, it doesn't _have_ to be used with pop-shell as the frontend, but it's not called system76-launcher.

**Comment by mmstick** [comment]
So cosmic-scheduler / cosmic-launcher might be a better fit?

**Comment by polarathene** [comment]
I kind of like `scheduler76`, ~~but `cosmic-scheduler` is probably more likely to get relevant results via a search engine query?~~ (**EDIT:** Actually `pop-scheduler` and `cosmic-scheduler` produced results from other domains that would need some extra keywords, while `system76-scheduler` is already producing top ranking results, meanwhile `scheduler76` top result is _"Maximo Scheduler 7.6"_). If search results matter at all, that might be worth pointing out.

---

I use Plasma, and have no experience with these projects or System76 hardware (_I am aware of the company, and roughly what they offer in hardware and software though_). At first it sounded like it's only meant as a scheduler associated to the project name from each suggestion. `system76-scheduler` seems most appropriate (_system76 probably ranks well as a keyword related to linux more than pop or cosmic, if that matters at all_).

It sounds like other shells could adopt support for it in future, and having `pop`/`cosmic` when not using anything else from those projects might seem more out of place than `system76`? (_doesn't bother me either way_)
