### ISSUE TITLE
[Question] How to install on regular Ubuntu?

### ISSUE THREAD

**Issue by DeicPro** [pop-os/system76-scheduler#40]
I would rather install it on my regular Ubuntu distro.

**Comment by mmstick** [comment]
1. `git clone https://github.com/pop-os/system76-scheduler`
2. Install the build-depends declared in `debian/control`
3. `dpkg-buildpackage -b`
4. `sudo dpkg -i ../system76-scheduler_*.deb`

**Comment by maxiberta** [comment]
My 2 cents: I'm using [this PPA with daily builds](https://launchpad.net/~maxiberta/+archive/ubuntu/system76-scheduler). It works great on KDE Plasma with [this KWin script](https://store.kde.org/p/1789957), fwiw.

Disclaimer: I'm the author of both the PPA and the KWin script :-)
