### ISSUE TITLE
Fullscreen applications and applications that use the webcam/mic should always be counted as foreground.

### ISSUE THREAD

**Issue by freyjadomville** [pop-os/system76-scheduler#42]
Hi,

Running Pop!_OS 22.04 to try out the scheduler on lower end hardware (Haswell ultrabook i7 processor, 2C/4T). Providing some feedback: 

- If I'm on a VoIP call (Discord, Telegram), my intuition is that the call should always be counted as a foreground process whilst the call is happening. 
- Similarly, any application that is full-screen should be considered as a foreground process, like a video maximised in a browser. 

In both cases, you get video/audio hitches when interacting with an application on a second screen, which detracts from the experience.

I'd offer a PR but my experience with Rust and dbus is minimal.

Hope this helps!

**Comment by mmstick** [comment]
Have you tried adding these to a config so they're always at least neutral in priority?
