### ISSUE TITLE
[Feature Request] Add support for mainline kernel (Xanmod-Edge for example)

### ISSUE THREAD

**Issue by gabriele2000** [pop-os/system76-scheduler#45]
Basically I use linux-xanmod-edge and when I type `system76-scheduler daemon` the result is `Error: kernel does not support tweaking the scheduler`.

As far as I understand, so far it's useless for now with xanmod, right?

**Comment by mmstick** [comment]
Xanmod isn't a mainline kernel, and it doesn't support the CFS tweaking feature. This message is warning about that feature not being supported by the kernel.

**Comment by gabriele2000** [comment]
So should I propose a change?

> Xanmod isn't a mainline kernel
That's new, since the edge branch it not the "tt" branch (TaskType scheduler)

**Comment by xanmod** [comment]
The xanmod's cfs sysctl parameters are the same as mainlline, only the energy efficiency functions have been removed.
https://github.com/xanmod/linux/commit/12cf86a1b23ccb8871d3cea8955916cd48be91cc

**Comment by xanmod** [comment]
https://github.com/pop-os/system76-scheduler/blob/c103229b9182dcbcef13c6f65160beddb02df46b/daemon/src/paths.rs#L7

[# CONFIG_PREEMPT_DYNAMIC is not set](https://github.com/xanmod/linux/blob/d88d798ad7acf37bf3db93378cdb59c456baa629/CONFIGS/xanmod/gcc/config_x86-64#L127)
In xanmod config it is not possible to change via debugfs.

Enabling preempt_dynamic in recent versions of linux forces the kernel to work in preempt and not preempt_voluntary as we wish. For this reason it is disabled.
