### ISSUE TITLE
Using `nice` from Tilix does nothing

### ISSUE THREAD

**Issue by robobenklein** [pop-os/system76-scheduler#59]
For terminals in focus, all their descendants acquire the same priority values when changed, however this makes using `nice` for a command completely useless.

Two commands being tested: `stress -c 8` and `nice stress -c 8` both end up with foreground priority/niceness `-5`, while obviously the `nice`d command should not be given priority.

Demo, foreground window name in top left:

https://user-images.githubusercontent.com/5423266/172304053-0bc8cf0f-5c26-4547-ab3e-4af214285680.mp4

**Comment by mmstick** [comment]
Try out #60

**Comment by robobenklein** [comment]
With #60 `nice stress` starts out with nice value 5, but changing focus away and then back to the terminal causes it to become `-5` again.
