### ISSUE TITLE
Broken link in synaptic

### ISSUE THREAD

**Issue by tititiou36** [pop-os/system76-scheduler#6]
Synaptic provides a link to home page for packages. In case of packages related to system76, it ends on github.
The link for system76-scheduler is broken and give an 404 error.

It is https://github.com/pop-os/scheduler instead of https://github.com/pop-os/system76-scheduler

(Not sure it is the correct place to report it, but I've no idea of where this should be updated)

**Comment by jacobgkau** [comment]
This should be adjustable here: https://github.com/pop-os/system76-scheduler/blob/4b77ff4c2892fc623bd2dd197a7b59d51a36d6e3/debian/control#L10

**Comment by tititiou36** [comment]
Thx. I've proposed a PR.
So this issue can be closed.
