### ISSUE TITLE
Why setuid binary?

### ISSUE THREAD

**Issue by jirutka** [pop-os/system76-scheduler#61]
Why is `/usr/bin/system76-scheduler` installed as a setuid binary (chmod 04755)? It runs as a system service under root, doesn’t it?

Is it possible to run it as a non-privileged user (without setuid ofc)? Also, what linux capabilities does it actually need?

**Comment by mmstick** [comment]
It only requires to be run as root by systemd

**Comment by jirutka** [comment]
Can you please elaborate a little more on that and answer the setuid question?

**Comment by mmstick** [comment]
Not much to add. It requires root because the daemon adjusts processes of all users, and some of which is setting a higher priority than permitted by the non-root user.

**Comment by jirutka** [comment]
Okay, but why is it installed with setuid bit? This has serious security implications, it allows _any_ user to run system76-scheduler with root privileges.

**Comment by jackpot51** [comment]
I agree with @jirutka it should not be `setuid`

**Comment by jackpot51** [comment]
@jirutka how do you have it installed? On my Pop!_OS install it is not `setuid`

**Comment by jackpot51** [comment]
```
$ ls -lah /usr/bin/system76-scheduler
-rwxr-xr-x 1 root root 5.7M Jun  7 03:43 /usr/bin/system76-scheduler
```

**Comment by jirutka** [comment]
[justfile:41](https://github.com/pop-os/system76-scheduler/blob/755612b824d58d5bde132b4856575fc6d4fd944a/justfile):

```
install -Dm04755 target/{{target}}/{{binary}} {{target_bin}}
```

**Comment by jackpot51** [comment]
@mmstick please make a PR to use `0755` as the mode
