### ISSUE TITLE
How to set `EXECSNOOP_PATH` to `/usr/share/bcc/tools/execsnoop` on Fedora 36

### ISSUE THREAD

**Issue by nlpsuge** [pop-os/system76-scheduler#64]
Hi, 

I'm using Fedora 36 and how I cannot find `execsnoop-bpfcc`, so I installed `bcc` which contains `execsnoop`. I'm not fully understand what are the difference they are. 

I checked this PR https://github.com/pop-os/system76-scheduler/pull/41, but I still don't understand how to config `EXECSNOOP_PATH`. 

`EXECSNOOP_PATH=/usr/share/bcc/tools/execsnoop` before running `just` does not work for me, see these errors:
```
error: must set EXECSNOOP_PATH env to execsnoop-bpfcc path
  --> execsnoop/src/lib.rs:42:18
   |
42 |       Command::new(std::env!(
   |  __________________^
43 | |         "EXECSNOOP_PATH",
44 | |         "must set EXECSNOOP_PATH env to execsnoop-bpfcc path"
45 | |     ))
   | |_____^
   |
   = note: this error originates in the macro `std::env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `execsnoop` due to previous error
error: Recipe `all` failed on line 24 with exit code 101
```

And advice?

**Comment by mmstick** [comment]
You have to export the variable

```
export EXECSNOOP_PATH=/usr/share/bcc/tools/execsnoop
just
```
or explicitly invoke just with it.

```
env EXECSNOOP_PATH=/usr/share/bcc/tools/execsnoop just

**Comment by mmstick** [comment]
I might be able to make it configurable in the just file.
