### ISSUE TITLE
Do the CFS features work with the CacULE schduler?

### ISSUE THREAD

**Issue by duplexsystem** [pop-os/system76-scheduler#7]
Do the CFS features work with the CacULE scheduler as it's a modified version of CFS

**Comment by ptr1337** [comment]
Hey, 

You can simply use this repo which does mostly the same as the systemd76 scheduler:

There you can also adjust the values to your wishes,

https://github.com/igo95862/cfs-zen-tweaks/blob/72bee98170135b062e431a74952e1d0c8110a87d/set-cfs-zen-tweaks.sh#L20

For the niceness levels you can use and many other features you can use :

https://gitlab.com/ananicy-cpp/ananicy-cpp

paired with the rules from the original ananicy project or create your own one to your wishes. 

With this setup, i can say you that it works great. Maybe i'll adjust some values in the future to include these values automatically into the scheduler. 

Here you can find the latest patches:

 https://github.com/CachyOS/cacule-cpu-scheduler
 
 Regards

**Comment by mmstick** [comment]
@ptr Neither of these do what system76-scheduler is doing

The real answer is yes.
