### ISSUE TITLE
Feature Request: allow disabling CFS tweaks

### ISSUE THREAD

**Issue by BayLee4** [pop-os/system76-scheduler#74]
It would be great to allow disabling CFS tweaks, as it would help when it's already handled manually, or more simply when one doesn't want to change the default which comes with its kernel. 

A `use_cfstweaks: true|false` in the `config.ron` would be perfect

**Comment by mmstick** [comment]
A new config format will be used that will look like this:

```kdl
// CFS latency adjustments
cfs enable=true {
    default latency=6 nr-latency=8 wakeup_granularity=1.0 bandwidth-size=5 preempt="voluntary"
    responsive latency=4 nr-latency=10 wakeup_granularity=0.5 bandwidth-size=3 preempt="full"
}
```
