### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by cmm** [pop-os/system76-scheduler#84]
According to my observations the boost-foreground-deboost-background logic takes precedence over the pipewire-client-boost logic, which does not seem terribly useful.

I wonder if there is a way to work around this?  I mean I can just disable the fg/bg logic altogether, thankfully, but that's a sledgehammer.

**Comment by cmm** [comment]
Disabling fg/bg does not seem to make a difference, in that the player (which thinks it's using pulseaudio, so presumably pipewire-pulse?) now stays at nice 0.

How does one debug this?  Does the daemon have some sort of verbose logging or something?

**Comment by cmm** [comment]
> What media player can I test with?

Deadbeef or Audacious (tried the latter with pipewire & pulse output, same difference)

Note that I'm not on PopOS (I use NixOS), so perhaps the output-to-pipewire detecting logic just doesn't work for some reason?

**Comment by mmstick** [comment]
It may be the case that system paths to the pipewire socket aren't in the same location. These applications work fine in Pop!_OS.

The scheduler is searching for all user session sockets accessible from [/run/user/{{UUID}}/pipewire-0](https://github.com/pop-os/system76-scheduler/blob/master/daemon/src/pw.rs#L55), such as `/run/user/1000/pipewire-0`.

**Comment by cmm** [comment]
The socket is definitely exactly there -- NixOS is _different_, but not _that_ different.
I'll try to add some logs, I guess...

**Comment by cmm** [comment]
OK it just started working after I added "RUST_LOG=debug" to the server environment.  No idea what that was about; will keep monitoring occasionally and will reopen if I find out anything.

For now, sorry about the noise!

**Comment by cmm** [comment]
So this was mostly a packaging issue on my part after all, but with a couple of takeaways that you may or may not find actionable.

Issue: scheduler needs to have itself in PATH in order to spawn the PW monitor.  NixOS has no central location like /usr/bin/ that is in everything's PATH (it's a core design decision), so scheduler could not find itself by name when run as a service.  I fixed the service definition.

Takeaways:
- spawning by name is meh, "/proc/self/exe" would be more reliable (and also renaming-resistant)
- an error message upon failure to spawn would... not hurt

**Comment by mmstick** [comment]
Want to create a PR for this?
