### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by MostHated** [pop-os/system76-scheduler#94]
Hey there, I just wanted to report this since I happened to notice it.

Not sure if the schedulers memory usage is because of pipewire, or vice versa?

![](https://img.instance.id/R76cox4wm2TQ/direct)

**Comment by mmstick** [comment]
Which version? Memory usage issues were fixed in the most recent update

**Comment by mmstick** [comment]
Same as #95

**Comment by mmstick** [comment]
Watch for https://github.com/pop-os/repo-release/pull/242
