### ISSUE TITLE
High CPU usage + high laptop temps

### ISSUE THREAD

**Issue by yassine-cc** [pop-os/system76-scheduler#95]
For the last couple of days, my laptop has seen a huge  increase in temperatures, and the cause seems to be the high cpu usage of system76-scheduler, killing it immediately reduces cpu usage dramatically and lowers temperatures

```
system76-scheduler:
  Installed: 2.0.0~1682509199~22.04~97a8617
  Candidate: 2.0.0~1682509199~22.04~97a8617
  Version table:
 *** 2.0.0~1682509199~22.04~97a8617 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by mmstick** [comment]
This was resolved by https://github.com/pop-os/system76-scheduler/pull/92

**Comment by mmstick** [comment]
Watch for https://github.com/pop-os/repo-release/pull/242
