### ISSUE TITLE
On occasion, very high CPU usage

### ISSUE THREAD

**Issue by MoonBurst** [pop-os/system76-scheduler#96]
Not so long ago I started using Wayland and sway WM, anyway, while running Overwatch 2, I noticed one of my CPU cores maxing out. That's unusual. With a quick trip into gnome-system-monitor, I found that the 76 manager was using 10% of my Ryzen 5 3600. That's abnormally high, and I don't really know what's up with it. But that event made me close it out for a while, and sometimes it'll rocket itself back up to that level.

**Comment by mmstick** [comment]
Watch for https://github.com/pop-os/repo-release/pull/242
